esphome:
  name: esp32-garage
  friendly_name: esp32-garage

esp32:
  board: nodemcu-32s
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_garage

ota:
  - platform: esphome
    password: !secret ota_garage

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Garage Fallback Hotspot"
    password: !secret fallback_garage

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: WiFi Signal dB
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    id: wifi_signal_pc
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

# state of the door : 5V: open (even not fully) or opening; 0V closed
binary_sensor:
  - platform: gpio
    device_class: garage_door
    id: garage_sensor
    pin:
      number: 4
      mode: INPUT
      inverted: false
    name: Garage door sensor
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms

#button works better tha switch
output:
  - platform: gpio
    pin:
      number: GPIO22
      inverted: True
    id: open_gpio
  - platform: gpio
    pin:
      number: GPIO21
      inverted: True
    id: close_gpio
button:
  - platform: output
    name: "Garage door Open button"
    id: garage_button_open
    output: open_gpio
    duration: 200ms
  - platform: output
    name: "Garage door Close button"
    id: garage_button_close
    output: close_gpio
    duration: 200ms
    
cover:
  - platform: template
    name: "Garage door state"
    id: garage_door_state
    open_action:
      - button.press: garage_button_open
    close_action:
      - button.press: garage_button_close
    lambda: |-
      if (id(garage_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
